#!/bin/sh
# prerm script for perfsonar host metrics
#
# see: dh_installdeb(1)

set -e


case "$1" in
    remove|upgrade|deconfigure)
        if [ -e /usr/share/apache2/apache2-maintscript-helper ]; then
            . /usr/share/apache2/apache2-maintscript-helper
            apache2_invoke disconf apache-node_exporter
            apache2_invoke disconf apache-perfsonar_host_exporter
        fi

        rm -f /var/www/html/perfsonar/host_exporter/host_exporter
    ;;
esac

exit 0