#
# Makefile for Unibuild Hello
#

UNAME_P := $(shell uname -p)

default: build

build:
	@echo Nothing to do here.

install:
	install -m 555 bin/node_exporter.$(UNAME_P) bin/node_exporter
	@echo Nothing to do here.

clean:
	@echo Nothing to do here.
