#
# Makefile for Unibuild Hello
#

UNAME_M := $(shell uname -m)

default: build

build:
	@echo Nothing to do here.

install:
	install -m 555 bin/node_exporter.$(UNAME_M) bin/node_exporter
	@echo Nothing to do here.

clean:
	@echo Nothing to do here.
